name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # или ветка, на которую вы хотите реагировать

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/face-detection:${{ github.sha }} .

      # Шаг 5: Пушим образ в Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/face-detection:${{ github.sha }}

      # Шаг 6: Помечаем образ как последний тег
      - name: Tag and push latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/face-detection:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/face-detection:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/face-detection:latest
